import { chromium } from 'playwright';
const base = process.argv[2] || 'http://127.0.0.1:5175';
const email = process.argv[3] || 'admin@test.local';
const pass = process.argv[4] || 'adminpass123';
const out = process.argv[5] || 'auth.json';
const b = await chromium.launch();
const ctx = await b.newContext();
const p = await ctx.newPage();
await p.goto(base + '/login', { waitUntil: 'domcontentloaded', timeout: 30000 });
await p.waitForSelector('#email', { timeout: 20000 });
await p.fill('#email', email);
await p.fill('#password', pass);
await p.click('button[type="submit"]');
await p.waitForURL(u => !u.pathname.startsWith('/login'), { timeout: 20000 });
await p.waitForSelector('main, .mantine-AppShell-main, aside, nav', { timeout: 20000 });
await p.waitForTimeout(1500);
await ctx.storageState({ path: out });
await b.close();
console.log('storageState ->', out);
