import { chromium } from 'playwright';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const TOOLS = dirname(fileURLToPath(import.meta.url));
const b = await chromium.launch();
const c = await b.newContext({ locale:'en-US', storageState: join(TOOLS,'auth.json') });
const p = await c.newPage();
p.on('console', m => { if (m.type()==='error') console.log('CONSOLE:', m.text().slice(0,300)); });
p.on('pageerror', e => console.log('PAGEERR:', e.message.slice(0,300)));
await p.goto('http://localhost:9400/t/personal_ehonlsofkmxlrfxy/documents/envelope_eznfzetwcsxxsmia/edit',{waitUntil:'load',timeout:90000});
await p.waitForSelector('main',{timeout:90000});
await p.waitForTimeout(2500);
const btns = await p.evaluate(()=>[...document.querySelectorAll('button')].filter(b=>/Document Settings/.test(b.innerText||'')).map(b=>b.outerHTML.slice(0,150)));
console.log('BTNS:',JSON.stringify(btns,null,1));
const t = p.locator('button', { hasText: 'Document Settings' }).first();
console.log('count:', await t.count());
await t.click({timeout:8000}).catch(e=>console.log('CLICKERR:',e.message.slice(0,200)));
await p.waitForTimeout(4000);
console.log('dialogs:', await p.locator('[role="dialog"]').count());
await b.close();
